---
- hosts: all
  vars:
    settings:
      nfs_host: 192.168.0.5
      nfs_torrent_path: "/mnt/user/k8s/torrent"
      nfs_adguard_path: "/mnt/user/k8s/adguard"
      nfs_multi_share_path: "/mnt/user/k8s/nfs-share"
  roles:
    - common

- hosts: masters
  roles:
    - kubemaster

- hosts: workers
  roles:
    - kubeworkers

- hosts: masters
  roles:
    - basics